url: 
baseurl: 

# Site settings
title: The WNDX Group Inc
email: talk-to-us@wndx.com
description: "Welcome to the home of The WNDX Group Inc, where Practical Software Development is our way of life."

collections:
  projects:
    output: true

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty